# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QR Directory Manager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ImageScrollView'
  pod 'MTBBarcodeScanner'

  # Pods for QR Directory Manager

end
